### ISSUE TITLE
Error by using sh scenario in eTraGo with func data_manipulation_sh()

### ISSUE THREAD

**Issue by wolfbunke** [openego/eTraGo#191] opened 2018-07-02 11:32 UTC
By using the SH scenario I got following Error:

```
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
WARNING:pypsa.components:The bus name `25536` given for bus0 of Transformer `nan` does not appear in network.buses
WARNING:pypsa.components:The bus name `26387` given for bus0 of Line `nan` does not appear in network.buses
Traceback (most recent call last):
  File "/home/dozeumbuw/eGo_release0.2/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2483, in get_value
    return libts.get_value_box(s, key)
  File "pandas/_libs/tslib.pyx", line 923, in pandas._libs.tslib.get_value_box (pandas/_libs/tslib.c:18843)
  File "pandas/_libs/tslib.pyx", line 932, in pandas._libs.tslib.get_value_box (pandas/_libs/tslib.c:18477)
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ego_main.py", line 72, in <module>
    eTraGo = etrago(args['eTraGo'])
  File "/home/dozeumbuw/eGo_release0.2/lib/python3.5/site-packages/etrago/appl.py", line 348, in etrago
    data_manipulation_sh(network)
  File "/home/dozeumbuw/eGo_release0.2/lib/python3.5/site-packages/etrago/tools/utilities.py", line 340, in data_manipulation_sh
    buses.geom['26387']), point_bus1])]), 4326))
  File "/home/dozeumbuw/eGo_release0.2/lib/python3.5/site-packages/pandas/core/series.py", line 601, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/dozeumbuw/eGo_release0.2/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2491, in get_value
    raise e1
  File "/home/dozeumbuw/eGo_release0.2/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2477, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 98, in pandas._libs.index.IndexEngine.get_value (pandas/_libs/index.c:4404)
  File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value (pandas/_libs/index.c:4087)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
KeyError: '26387'

```
see also: https://github.com/openego/eTraGo/blob/dev/etrago/tools/utilities.py#L317-L354

**Comment by BartelsJ** [comment] 2018-07-11 16:19
I reproduced this. Anyone working on this issue yet?

**Comment by lukasoldi** [comment] 2018-07-12 13:19
This is probably due to the fact that there is no data scenario for SH after version 'v0.2.11'. Must be created via dataprocessing.

**Comment by BartelsJ** [comment] 2018-08-24 08:58
Thanks for the hint! I close this issue

**Closed by BartelsJ** 2018-08-24 08:58 UTC
