### ISSUE TITLE
Elements in "links_t" without a correspondig object in "links"

### ISSUE THREAD

**Issue by CarlosEpia** [openego/eTraGo#396] opened 2022-03-21 13:49 UTC
After running etrago.kmean_clustering_gas() this warning appears:

`WARNING:pypsa.io:Components Index(['100', '103', '105', '107', '115', '117', '119', '12', '125', '127',
       ...
       '81', '82', '83', '84', '85', '86', '91', '93', '95', '97'],
      dtype='object', name='Link', length=149) for attribute efficiency of Link are not in main components dataframe links`

After checking the mentioned tables, it was found that in the table etrago.network.links_t['efficiency'] there are some elements without an associated link in etrago.network.links.

**Comment by CarlosEpia** [comment] 2022-03-21 13:51
@fwitte I remember last week it was necessary to do some modifications in the aggregation of links in the gas clustering. Could this be related?

**Comment by CarlosEpia** [comment] 2022-03-22 08:40
Hi, @fwitte I'm currently using the SH test case. I think that the problem could be here: https://github.com/openego/eTraGo/blob/dc455ab47da32b32ed9fca6eb3c83c111a30fc6c/etrago/cluster/gasclustering.py#L445-L448
Once the links are aggregated, the tables inside network.links_t are imported directly from the original network, but I think we need to consider that some aggregated links don't exist anymore. The gas-busmap should be used to deal with the time-dependent data too.

**Comment by fwitte** [comment] 2022-03-22 09:55
@CarlosEpia, thank you for digging into it, can we work on this together tomorrow before 09:00 or after 13:30?

**Comment by CarlosEpia** [comment] 2022-03-22 10:33
Sure. 13:30 would be ok for me.

**Comment by fwitte** [comment] 2022-03-23 07:02
I do think that this is a duplicate of https://github.com/openego/eTraGo/issues/382

**Comment by CarlosEpia** [comment] 2022-03-23 07:27
> I do think that this is a duplicate of #382

Totally agree. I will close #382.

**Comment by CarlosEpia** [comment] 2022-06-17 12:06
Hi @fwitte. Is there news about this issue?

**Comment by fwitte** [comment] 2022-06-21 06:56
Hi @CarlosEpia, unfortunately no news on this one.

**Comment by ClaraBuettner** [comment] 2022-06-30 10:22
I'm sorry for asking again, but did you already made some progress here? 
This issue is currently preventing us from running eTraGo-caluclations with e-mobility...

**Closed** 2022-07-19 06:38 UTC
